# maintainer: sebastian
version: "3"
services:
  goeserver:
#  image: mightymarabu/postgresql_extended
    image: oscarfonts/geoserver:latest
    deploy:
      replicas: 3
      resources:
         limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8181:8080"
    networks:
      - supertestnet
  visualizer:
    image: mightymarabu/postgresql_extended
    ports:
      - "5432:5432"
    deploy:
      replicas: 2
    networks:
      - supertestnet
networks:
  supertestnet:
