version: "3"
services:
  web:
#  image: mightymarabu/postgresql_extended
    image: mightymarabu/otm:develop
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "7001:80"
    networks:
      - testnet
networks:
  testnet:
